title: <p align="center"> Sivasankar </p>
logo: /assets/logo/My Photo New.jpg
description:
  <p align="center">
  <a href="docs/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/siva-sankar-june1984/">LinkedIn</a> |
  <a href="https://github.com/sivasan002/">GitHub</a>
show_downloads: true

theme: jekyll-theme-minimal
